---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name:  staging
spec:
  acme:
    # staging env : letencrypt
    email: ons.hanafi2@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name:  staging-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: external-nginx