---
# Use only after validating the staging certificate
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name:  production
spec:
  acme:
    email: ons.hanafi2@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name:  production-cluster-issuer
    solvers:
      - selector: {}
        http01:
          ingress:
            class: external-nginx